02-14-2021-23-50-16[ss][EXCEPTION]: Traceback (most recent call last):
  File "/home/spotify/projects/zeus/src/services/driversadapter/chrome.py", line 142, in getNewInstance
    driver.execute_script(script)
  File "/home/spotify/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "/home/spotify/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/spotify/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=85.0.4183.83)


